import { AppText as Text } from '../../src/components';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { ScrollView, StyleSheet, Text as RNText, View } from 'react-native';
import { useAuth } from '../../src/auth';
import { api } from '../../src/api';
import { ErrorState, Skeleton, StatusPill } from '../../src/components';
import { colors, useTheme, radii } from '../../src/theme';
const money = (v) => 'ETB ' + Number(v).toLocaleString('en-US', { minimumFractionDigits: 2 });
export default function LoanDetail() { const { colors: themeColors } = useTheme(); s = createStyles(themeColors); const { id } = useLocalSearchParams(); const { token } = useAuth(); const q = useQuery({ queryKey: ['loan', id], queryFn: () => api.loan(token, id), enabled: !!token && !!id }); if (q.isError)
    return <ErrorState message="We couldn’t load this loan." retry={() => q.refetch()}/>; if (q.isLoading || !q.data)
    return <View style={s.loading}><Skeleton width="100%" height={180} /><View style={{ gap: 14, width: '100%', marginTop: 18 }}><Skeleton width="70%" height={24} /><Skeleton width="90%" height={16} /><Skeleton width="90%" height={16} /></View></View>; const l = q.data; return <ScrollView style={s.page} contentContainerStyle={s.content}><Ionicons onPress={() => router.back()} name="arrow-back" size={24} color={colors.ink}/><View style={s.head}><View><Text style={s.overline}>LOAN DETAILS</Text><Text style={s.title}>{l.type === 'self_secured' ? 'Self-secured loan' : 'Regular loan'}</Text></View><StatusPill status={l.status}/></View><View style={s.hero}><Text style={s.heroLabel}>PRINCIPAL</Text><Text style={s.heroAmount}>{money(l.principal_amount)}</Text><Text style={s.heroSub}>{l.term_years}-year term · {l.interest_rate}% interest</Text></View><View style={s.grid}>{[['Monthly installment', money(l.monthly_installment)], ['Monthly interest', money(l.monthly_interest_amount)], ['Insurance', money(l.insurance_amount)], ['Collateral', l.collateral_type === 'guarantor' ? 'Guarantor' : 'Property']].map(([a, b]) => <View style={s.cell} key={a}><Text style={s.cellLabel}>{a}</Text><Text style={s.cellValue}>{b}</Text></View>)}</View><Text style={s.note}>Loan applications are reviewed by the cooperative office. We’ll notify you when the status changes.</Text></ScrollView>; }
let s;
const createStyles = (colors) => StyleSheet.create({ page: { flex: 1, backgroundColor: colors.canvas }, content: { padding: 20, paddingTop: 22, paddingBottom: 34 }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.canvas }, sub: { fontSize: 14, color: colors.muted }, head: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginVertical: 26 }, overline: { fontSize: 11, fontWeight: '900', letterSpacing: 1.3, color: colors.greenBright }, title: { fontSize: 26, fontWeight: '900', color: colors.ink, marginTop: 6 }, hero: { backgroundColor: colors.green, borderRadius: radii.card, padding: 22 }, heroLabel: { fontSize: 11, fontWeight: '900', letterSpacing: 1.2, color: colors.mintStrong }, heroAmount: { fontSize: 34, fontWeight: '900', color: '#FFF', marginTop: 13 }, heroSub: { fontSize: 13, color: '#D8F2E6', marginTop: 8 }, grid: { backgroundColor: colors.surface, borderRadius: radii.card, marginTop: 14, padding: 5, flexDirection: 'row', flexWrap: 'wrap' }, cell: { width: '50%', padding: 15, borderBottomWidth: 1, borderRightWidth: 1, borderColor: colors.line }, cellLabel: { fontSize: 12, color: colors.muted }, cellValue: { fontSize: 14, fontWeight: '800', color: colors.ink, marginTop: 7 }, note: { fontSize: 13, lineHeight: 20, color: colors.muted, marginTop: 20, paddingHorizontal: 4 } });
