import { Ionicons } from '@expo/vector-icons';
import { Modal, Pressable, StyleSheet, Text as RNText, View } from 'react-native';
import { colors, radii, shadow, useTheme } from './theme';
import { translatePhrase, useLanguage } from './language';
export function AppText({ children, style, ...props }) {
    const { language, isAmharic } = useLanguage();
    useTheme();
    const flattenedStyle = StyleSheet.flatten(style) || {};
    const weight = flattenedStyle.fontWeight === 'bold' ? 700 : Number(flattenedStyle.fontWeight) || 400;
    const amharicFont = weight >= 800 ? 'SurGraphicsExtraBold' : weight >= 600 ? 'SurGraphicsBold' : 'SurGraphicsRegular';
    const amharicStyle = isAmharic ? { fontFamily: amharicFont, fontWeight: 'normal' } : null;
    const translated = typeof children === 'string'
        ? translatePhrase(children, language)
        : Array.isArray(children)
            ? children.map((child, index) => typeof child === 'string'
                ? <RNText key={index} style={amharicStyle}>{translatePhrase(child, language)}</RNText>
                : child)
            : children;
    return <RNText {...props} style={[style, amharicStyle]}>{translated}</RNText>;
}
export function Screen({ children, title, subtitle, right, scroll = false }) {
    const { colors: themeColors } = useTheme();
    styles = createStyles(themeColors);
    const content = <View style={styles.screen}>{title && <View style={styles.header}><View><AppText style={styles.title}>{title}</AppText>{subtitle && <AppText style={styles.subtitle}>{subtitle}</AppText>}</View>{right}</View>}{children}</View>;
    return scroll ? <View style={{ flex: 1, backgroundColor: colors.canvas }}>{content}</View> : content;
}
export function Button({ children, variant = 'primary', style, ...props }) { const { colors: themeColors } = useTheme(); styles = createStyles(themeColors); return <Pressable {...props} style={({ pressed }) => [styles.button, variant === 'secondary' && styles.secondaryButton, pressed && styles.pressed, style]}><AppText style={[styles.buttonText, variant === 'secondary' && styles.secondaryText]}>{children}</AppText></Pressable>; }
export function IconButton({ name, onPress, badge }) { const { colors: themeColors } = useTheme(); styles = createStyles(themeColors); return <Pressable onPress={onPress} hitSlop={8} style={({ pressed }) => [styles.iconButton, pressed && styles.pressed]}><Ionicons name={name} size={21} color={themeColors.ink}/>{badge && <View style={styles.badge}/>}</Pressable>; }
export function SectionTitle({ children, action, onAction }) { return <View style={styles.sectionTitle}><AppText style={styles.sectionText}>{children}</AppText>{action && <Pressable onPress={onAction}><AppText style={styles.action}>{action}</AppText></Pressable>}</View>; }
export function StatusPill({ status }) { const { colors: themeColors } = useTheme(); styles = createStyles(themeColors); const map = { active: ['Active', themeColors.mint], pending: ['Pending', themeColors.amberSoft], closed: ['Closed', themeColors.line], rejected: ['Rejected', themeColors.redSoft] }; const [label, background] = map[status] ?? [status, themeColors.line]; return <View style={[styles.pill, { backgroundColor: background }]}><AppText style={styles.pillText}>{label}</AppText></View>; }
export function ErrorState({ message, retry }) { const { colors: themeColors } = useTheme(); styles = createStyles(themeColors); return <View style={styles.error}><Ionicons name="cloud-offline-outline" size={26} color={themeColors.red}/><AppText style={styles.errorText}>{message}</AppText><Button variant="secondary" onPress={retry}>Try again</Button></View>; }
export function Skeleton({ width = '100%', height = 18 }) { const { colors: themeColors } = useTheme(); styles = createStyles(themeColors); return <View style={[styles.skeleton, { width, height }]}/>; }
export function ThemedAlert({ visible, title, message, actions = [{ text: 'OK' }], onClose }) { const { colors: themeColors } = useTheme(); styles = createStyles(themeColors); return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={styles.alertBackdrop} onPress={onClose}><Pressable style={styles.alertCard} onPress={(event) => event.stopPropagation()}><AppText style={styles.alertTitle}>{title}</AppText>{message && <AppText style={styles.alertMessage}>{message}</AppText>}<View style={styles.alertActions}>{actions.map((action) => <Pressable key={action.text} onPress={() => { onClose?.(); action.onPress?.(); }} style={({ pressed }) => [styles.alertAction, pressed && styles.pressed]}><AppText style={[styles.alertActionText, action.variant === 'destructive' && styles.alertDestructive]}>{action.text}</AppText></Pressable>)}</View></Pressable></Pressable></Modal>; }
let styles;
const createStyles = (colors) => StyleSheet.create({ screen: { flex: 1, paddingHorizontal: 20, paddingTop: 18, backgroundColor: colors.canvas }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 22 }, title: { color: colors.ink, fontSize: 28, fontWeight: '800', letterSpacing: -0.7 }, subtitle: { color: colors.muted, fontSize: 14, marginTop: 5 }, sectionTitle: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, marginTop: 24 }, sectionText: { color: colors.ink, fontSize: 16, fontWeight: '800' }, action: { color: colors.greenBright, fontSize: 13, fontWeight: '700' }, button: { minHeight: 50, borderRadius: radii.control, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 }, secondaryButton: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line }, buttonText: { color: '#FFF', fontSize: 15, fontWeight: '800' }, secondaryText: { color: colors.green }, pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] }, iconButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.surface, justifyContent: 'center', alignItems: 'center', ...shadow }, badge: { position: 'absolute', top: 9, right: 10, width: 7, height: 7, borderRadius: 4, backgroundColor: colors.greenBright, borderWidth: 1, borderColor: colors.surface }, pill: { borderRadius: radii.pill, paddingHorizontal: 10, paddingVertical: 5 }, pillText: { color: colors.ink, fontSize: 12, fontWeight: '800' }, error: { alignItems: 'center', gap: 12, padding: 28 }, errorText: { color: colors.muted, textAlign: 'center', lineHeight: 20 }, skeleton: { backgroundColor: colors.line, borderRadius: 8, opacity: 0.7 }, alertBackdrop: { flex: 1, backgroundColor: 'rgba(4, 20, 15, 0.62)', justifyContent: 'center', padding: 24 }, alertCard: { backgroundColor: colors.surface, borderRadius: 24, padding: 24, shadowColor: colors.ink, shadowOpacity: 0.2, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 8 }, alertTitle: { color: colors.ink, fontSize: 22, lineHeight: 28, fontWeight: '900' }, alertMessage: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 12 }, alertActions: { flexDirection: 'row', justifyContent: 'flex-end', flexWrap: 'wrap', gap: 8, marginTop: 22 }, alertAction: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 12 }, alertActionText: { color: colors.greenBright, fontSize: 14, fontWeight: '900', letterSpacing: 0.7 }, alertDestructive: { color: colors.red } });
