import * as SecureStore from 'expo-secure-store';
import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const copy = {
  en: {
    language: 'Language', english: 'English', amharic: 'አማርኛ',
    memberAccess: 'MEMBER ACCESS', heading: 'Your cooperative,\nwithin reach.',
    loginBody: 'See your savings, shares and loans clearly — wherever you are.',
    phone: 'Phone number', password: 'Password', phonePlaceholder: '09 00 000 000',
    passwordPlaceholder: 'Enter your password', signIn: 'Sign in',
    signingIn: 'Signing in…', passwordHelp: 'Password issues? Visit the office to reset it.',
    almostThere: 'Almost there', required: 'Enter your phone number and password to continue.',
    couldNotSignIn: 'Could not sign in', incorrect: 'Your phone number or password isn’t right.',
    membershipInactive: 'Membership inactive', inactiveBody: 'Your membership is inactive. Please visit the office for help.',
    passwordNotSet: 'Password not set', passwordNotSetBody: 'Please visit the office to set a password for your account.',
    profile: 'Profile', membership: 'MEMBERSHIP', personalDetails: 'PERSONAL DETAILS', age: 'Age', gender: 'Gender', address: 'Address', heirInfo: 'HEIR INFORMATION', dateJoined: 'Member since', notProvided: 'Not provided',
    appearance: 'APPEARANCE', darkMode: 'Dark mode', darkModeHint: 'Use a darker appearance at night.',
    active: 'Active', changeLanguage: 'Change language', changePassword: 'Change password',
    logOut: 'Log out', cancel: 'Cancel', logOutQuestion: 'Log out?',
    logOutBody: 'You’ll need to sign in again to view your account.',
  },
  am: {
    language: 'ቋንቋ', english: 'English', amharic: 'አማርኛ',
    memberAccess: 'የአባል መግቢያ', heading: 'የእርስዎ ማህበር፣\nበእጅዎ ላይ።',
    loginBody: 'የቁጠባዎን፣ የአክሲዮንዎን እና የብድርዎን መረጃ በግልጽ ይመልከቱ።',
    phone: 'ስልክ ቁጥር', password: 'የይለፍ ቃል', phonePlaceholder: '09 00 000 000',
    passwordPlaceholder: 'የይለፍ ቃልዎን ያስገቡ', signIn: 'ግባ',
    signingIn: 'በመግባት ላይ…', passwordHelp: 'የይለፍ ቃል ችግር አለ? ለማስተካከል ወደ ቢሮ ይሂዱ።',
    almostThere: 'ትንሽ ቀርቷል', required: 'ለመቀጠል የስልክ ቁጥርዎን እና የይለፍ ቃልዎን ያስገቡ።',
    couldNotSignIn: 'መግባት አልተቻለም', incorrect: 'የስልክ ቁጥርዎ ወይም የይለፍ ቃልዎ ትክክል አይደለም።',
    membershipInactive: 'አባልነት ታግዷል', inactiveBody: 'አባልነትዎ ታግዷል። እባክዎ እርዳታ ለማግኘት ወደ ቢሮ ይሂዱ።',
    passwordNotSet: 'የይለፍ ቃል አልተዘጋጀም', passwordNotSetBody: 'እባክዎ የይለፍ ቃል ለማዘጋጀት ወደ ቢሮ ይሂዱ።',
    profile: 'መገለጫ', membership: 'አባልነት', personalDetails: 'የግል መረጃ', age: 'ዕድሜ', gender: 'ጾታ', address: 'አድራሻ', heirInfo: 'የወራሽ መረጃ', dateJoined: 'አባል የሆኑበት ቀን', notProvided: 'አልተሰጠም',
    appearance: 'ገጽታ', darkMode: 'ጨለማ ሁነታ', darkModeHint: 'በሌሊት የጨለመ ገጽታ ይጠቀሙ።',
    active: 'ንቁ', changeLanguage: 'ቋንቋ ቀይር', changePassword: 'የይለፍ ቃል ቀይር',
    logOut: 'ውጣ', cancel: 'ሰርዝ', logOutQuestion: 'ይውጡ?',
    logOutBody: 'የአባል መረጃዎን ለማየት እንደገና መግባት ያስፈልጋል።',
  },
  om: {
    language: 'Afaan', english: 'English', amharic: 'አማርኛ',
    memberAccess: 'SEENSA QAAMA', heading: 'Waldaan keessan,\nqaqqabamaa.',
    loginBody: 'Qusannaa, aksiyoonaa fi liqawwan keessanii ifatti ilaalaa.',
    phone: 'Lakkoofsa bilbilaa', password: 'Jecha icciitii', phonePlaceholder: '09 00 000 000',
    passwordPlaceholder: 'Jecha icciitii keessan galchaa', signIn: 'Seenaa',
    signingIn: 'Seenaa jira…', passwordHelp: 'Rakkoo jecha icciitii qabduu? Waajjira dhaqaatii haaromsi.',
    almostThere: 'Xiqqoo hafe', required: 'Itti fufuuf lakkoofsa bilbilaa fi jecha icciitii galchaa.',
    couldNotSignIn: 'Seenuun hin danda’amne', incorrect: 'Lakkoofsi bilbilaa ykn jechi icciitii sirrii miti.',
    membershipInactive: 'Miseensummaan dhaabbate', inactiveBody: 'Miseensummaan keessan dhaabbateera. Gargaarsaaf waajjira dhaqaa.',
    passwordNotSet: 'Jechi icciitii hin qophoofne', passwordNotSetBody: 'Jecha icciitii qopheessuuf waajjira dhaqaa.',
    profile: 'Profaayilii', membership: 'MISEENSUMMAA', personalDetails: 'ODEEFFANNOO DHUNFAA', age: 'Umurii', gender: 'Saala', address: 'Teessoo', heirInfo: 'ODEEFFANNOO DHAALTUU', dateJoined: 'Miseensa kan taatan', notProvided: 'Hin kennamne',
    appearance: 'MUL’ATA', darkMode: 'Haala dukkanaa', darkModeHint: 'Halkan mul’ata dukkanaa fayyadamaa.',
    active: 'Hojii irra', changeLanguage: 'Afaan jijjiiri', changePassword: 'Jecha icciitii jijjiiri',
    logOut: 'Ba’i', cancel: 'Haqi', logOutQuestion: 'Ba’uu?',
    logOutBody: 'Herrega keessan ilaaluuf irra deebitanii seenuu qabdu.',
  },
};

const phrases = {
  'Good morning': 'መልካም ጠዋት',
  'Good afternoon': 'መልካም ከሰዓት',
  'Good evening': 'መልካም ምሽት',
  'MEMBER HOME': 'የአባል መነሻ',
  'MONEY AT A GLANCE': 'የገንዘብ አጠቃላይ እይታ',
  'Your cooperative balance': 'የማህበሩ ቀሪ ሂሳብዎ',
  'Your balances': 'የእርስዎ ቀሪ ሂሳቦች',
  'Savings balance': 'የቁጠባ ቀሪ ሂሳብ',
  'Share balance': 'የአክሲዮን ቀሪ ሂሳብ',
  'Savings and shares held with your cooperative': 'ከማህበሩ ጋር ያሉ የቁጠባ እና የአክሲዮን ቀሪ ሂሳቦች',
  'Secure': 'ደህንነቱ የተጠበቀ',
  'total savings': 'ጠቅላላ ቁጠባ',
  'SAVINGS': 'ቁጠባ',
  'SHARES': 'አክሲዮን',
  'SHORTCUTS': 'አቋራጮች',
  'Apply for a loan': 'ለብድር ያመልክቱ',
  'When you’re ready, we’ll guide you through each step.': 'ዝግጁ ሲሆኑ በእያንዳንዱ ደረጃ እንመራዎታለን።',
  'View history': 'ታሪክ ይመልከቱ',
  'Open inbox': 'መልዕክቶችን ይክፈቱ',
  'Your plan': 'የእርስዎ ዕቅድ',
  'Details': 'ዝርዝር',
  'UNDER REVIEW': 'በግምገማ ላይ',
  'ACTIVE LOAN': 'ንቁ ብድር',
  'Self-secured loan': 'በራስ ዋስትና ብድር',
  'Regular loan': 'መደበኛ ብድር',
  'No loan in progress': 'በሂደት ላይ ብድር የለም',
  'Your next step is always up to you.': 'ቀጣዩ እርምጃ ሁልጊዜ በእርስዎ ምርጫ ነው።',
  'Recent activity': 'የቅርብ ጊዜ እንቅስቃሴ',
  'See all': 'ሁሉንም ይመልከቱ',
  'Your activity will appear here': 'የእንቅስቃሴ መረጃዎ እዚህ ይታያል',
  'No active loans': 'ንቁ ብድር የለም',
  'Loans': 'ብድሮች',
  'MEMBER FINANCE': 'የአባል የገንዘብ አገልግሎት',
  'Your applications and repayment plans': 'የእርስዎ ማመልከቻዎች እና የመክፈያ ዕቅዶች',
  'Your applications': 'የእርስዎ ማመልከቻዎች',
  'No applications yet': 'እስካሁን ማመልከቻ የለም',
  'History': 'ታሪክ',
  'Your membership, from every angle': 'የአባልነትዎ ሙሉ ታሪክ',
  'Transactions': 'ግብይቶች',
  'Dividends': 'ድርሻ ትርፍ',
  'ACTIVITY TYPES': 'የእንቅስቃሴ ዓይነቶች',
  'No transactions yet': 'እስካሁን ግብይት የለም',
  'No dividends yet': 'እስካሁን የድርሻ ትርፍ የለም',
  'Inbox': 'መልዕክቶች',
  'FROM YOUR COOPERATIVE': 'ከእርስዎ ማህበር',
  'Updates, reminders and loan decisions': 'ዝመናዎች፣ አስታዋሾች እና የብድር ውሳኔዎች',
  'You’re all caught up': 'ሁሉንም መልዕክቶች አንብበዋል',
  'Plan your loan': 'ብድርዎን ያቅዱ',
  'See the full cost before you send your application.': 'ማመልከቻዎን ከመላክዎ በፊት ሙሉ ወጪውን ይመልከቱ።',
  'Loan type': 'የብድር ዓይነት',
  'Regular': 'መደበኛ',
  'Self-secured': 'በራስ ዋስትና',
  'How much do you need?': 'ምን ያህል ያስፈልግዎታል?',
  'Repayment term': 'የመክፈያ ጊዜ',
  'Collateral': 'ዋስትና',
  'Property': 'ንብረት',
  'Guarantor': 'ዋስ',
  'Guarantor member ID': 'የዋስ አባል መለያ',
  'ESTIMATED COST': 'የተገመተ ወጪ',
  'What repayment looks like': 'የመክፈያ መጠን',
  'Principal': 'ዋና ገንዘብ',
  'Insurance (1%)': 'ኢንሹራንስ (1%)',
  'Estimated total repayment': 'የተገመተ ጠቅላላ ክፍያ',
  'Submit application': 'ማመልከቻ ይላኩ',
  'LOAN DETAILS': 'የብድር ዝርዝር',
  'PRINCIPAL': 'ዋና ገንዘብ',
  'Monthly installment': 'ወርሃዊ ክፍያ',
  'Monthly interest': 'ወርሃዊ ወለድ',
  'Insurance': 'ኢንሹራንስ',
  'Your phone number or password isn’t right.': 'የስልክ ቁጥርዎ ወይም የይለፍ ቃልዎ ትክክል አይደለም።',
  'Savings deposit': 'የቁጠባ ገቢ',
  'Share purchase': 'የአክሲዮን ግዢ',
  'Penalty payment': 'የቅጣት ክፍያ',
  'Registration fee': 'የምዝገባ ክፍያ',
  'Card fee': 'የካርድ ክፍያ',
  'Loan disbursement': 'የብድር ክፍያ መልቀቅ',
  'Loan payment': 'የብድር ክፍያ',
  'Loan interest': 'የብድር ወለድ',
  'Loan insurance': 'የብድር ኢንሹራንስ',
  'Exit payout': 'የመውጫ ክፍያ',
  'Bank interest': 'የባንክ ወለድ',
  'New updates from Tokuma Misomaf will appear here.': 'አዲስ መልዕክቶች ከቶኩማ ሚሶማፍ ሲላኩ እዚህ ይታያሉ።',
  'View loan': 'ብድሩን ይመልከቱ',
  'Close': 'ዝጋ',
};
const oromoPhrases = {
  'Good morning': 'Akkam bulte',
  'Good afternoon': 'Akkam ooltan',
  'Good evening': 'Akkam galgala',
  'MEMBER HOME': 'MANAA QAAMAA',
  'MONEY AT A GLANCE': 'MAALLAQA ILAALCHA TOKKOON',
  'Your cooperative balance': 'Haftee waldaa keessanii',
  'Your balances': 'Haftee keessan',
  'Savings balance': 'Haftee qusannaa',
  'Share balance': 'Haftee aksiyoonaa',
  'Savings and shares held with your cooperative': 'Qusannaa fi aksiyoonaa waldaa keessan bira jiru',
  'Secure': 'Nageenyaan',
  'total savings': 'qusannaa waliigalaa',
  'SAVINGS': 'QUSANNAA',
  'SHARES': 'AKSIYOONA',
  'SHORTCUTS': 'GABAABAA',
  'Apply for a loan': 'Liqii gaafadhu',
  'View history': 'Seenaa ilaali',
  'Open inbox': 'Ergaa bani',
  'Your plan': 'Karoora keessan',
  'Details': 'Bal’ina',
  'UNDER REVIEW': 'QORANNAA JALA',
  'ACTIVE LOAN': 'LIQII HOJII IRRA',
  'Self-secured loan': 'Liqii wabii ofii',
  'Regular loan': 'Liqii idilee',
  'No loan in progress': 'Liqiin adeemsa irra hin jiru',
  'Recent activity': 'Sochii dhihoo',
  'See all': 'Hunda ilaali',
  'Your activity will appear here': 'Sochiin keessan asitti mul’ata',
  'Loans': 'Liqiiwwan',
  'MEMBER FINANCE': 'TAJAAJILA MAALLAQAA QAAMAA',
  'Your applications and repayment plans': 'Gaaffilee fi karoora kaffaltii keessanii',
  'Your applications': 'Gaaffilee keessan',
  'No applications yet': 'Ammaaf gaaffiin hin jiru',
  'History': 'Seenaa',
  'Transactions': 'Daldalawwan',
  'Dividends': 'Bu’aa qoodamaa',
  'ACTIVITY TYPES': 'GOSA SOCHII',
  'No transactions yet': 'Ammaaf daldalli hin jiru',
  'No dividends yet': 'Ammaaf bu’aan qoodamaa hin jiru',
  'Inbox': 'Ergaa',
  'FROM YOUR COOPERATIVE': 'WALDAA KEESSAN IRRAA',
  'Updates, reminders and loan decisions': 'Oduu haaraa, yaadachiisa fi murtii liqii',
  'You’re all caught up': 'Ergaa hunda dubbistaniittu',
  'Plan your loan': 'Liqii keessan karoorfadhaa',
  'Loan type': 'Gosa liqii',
  'Regular': 'Idilee',
  'Self-secured': 'Wabii ofii',
  'How much do you need?': 'Hanga meeqa isin barbaachisa?',
  'Repayment term': 'Yeroo kaffaltii',
  'Collateral': 'Wabii',
  'Property': 'Qabeenya',
  'Guarantor': 'Wabsiisaa',
  'ESTIMATED COST': 'BAASII TILMAAMAME',
  'What repayment looks like': 'Kaffaltiin akkamitti akka ta’u',
  'Principal': 'Maallaqa ijoo',
  'Insurance (1%)': 'Inshuraansii (1%)',
  'Estimated total repayment': 'Kaffaltii waliigalaa tilmaamame',
  'Submit application': 'Gaaffii ergi',
  'Monthly installment': 'Kaffaltii ji’aa',
  'Monthly interest': 'Dhala ji’aa',
  'Insurance': 'Inshuraansii',
  'Savings deposit': 'Qusannaa galchuu',
  'Share purchase': 'Bittaa aksiyoonaa',
  'Penalty payment': 'Kaffaltii adabbii',
  'Registration fee': 'Kaffaltii galmee',
  'Card fee': 'Kaffaltii kaardii',
  'Loan disbursement': 'Liqii gad-lakkifame',
  'Loan payment': 'Kaffaltii liqii',
  'Loan interest': 'Dhala liqii',
  'Loan insurance': 'Inshuraansii liqii',
  'Exit payout': 'Kaffaltii ba’umsaa',
  'Bank interest': 'Dhala baankii',
  'New updates from Tokuma Misomaf will appear here.': 'Oduun haaraan Tokuma Misomaf irraa asitti mul’ata.',
  'View loan': 'Liqii ilaali',
  'Close': 'Cufi',
};
export function translatePhrase(value, language) {
  if ((language !== 'am' && language !== 'om') || typeof value !== 'string') return value;
  if (value.startsWith('ETB ')) return language === 'am' ? value.slice(4) + ' ብር ' : value.slice(4) + ' Birrii ';
  return (language === 'am' ? phrases[value] : oromoPhrases[value]) ?? value;
}

const LanguageContext = createContext(null);
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const [ready, setReady] = useState(false);
  useEffect(() => { SecureStore.getItemAsync('member_language').then((saved) => { if (saved === 'en' || saved === 'am' || saved === 'om') setLanguage(saved); }).finally(() => setReady(true)); }, []);
  const changeLanguage = async (next) => { setLanguage(next); await SecureStore.setItemAsync('member_language', next); };
  const value = useMemo(() => ({ language, ready, isAmharic: language === 'am', isOromo: language === 'om', t: (key) => copy[language][key] ?? copy.en[key] ?? key, changeLanguage }), [language, ready]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export function useLanguage() { const value = useContext(LanguageContext); if (!value) throw new Error('useLanguage must be used inside LanguageProvider'); return value; }
