export const LANGUAGES = {
  en: { label: "English", nativeLabel: "English" },
  am: { label: "Amharic", nativeLabel: "አማርኛ" },
}

// Static UI copy used throughout the admin portal. Dynamic values remain in
// their original form, while surrounding labels are translated consistently.
export const translations = {
  "Overview": "አጠቃላይ እይታ",
  "Dashboard": "ዳሽቦርድ",
  "Operations": "ስራዎች",
  "Members": "አባላት",
  "Transactions": "ግብይቶች",
  "Expenses": "ወጪዎች",
  "Member exits": "የአባላት መውጫ",
  "Administration": "አስተዳደር",
  "Dividends": "የትርፍ ድርሻ",
  "Notifications": "ማሳወቂያዎች",
  "Synchronization": "ማመሳሰያ",
  "Administrators": "አስተዳዳሪዎች",
  "Settings": "ቅንብሮች",
  "Management portal": "የአስተዳደር መተግበሪያ",
  "Sign out": "ውጣ",
  "Good morning,": "እንደምን አደሩ፣",
  "Here is today’s cooperative overview.": "የዛሬ የህብረት ስራ ማህበሩ አጠቃላይ እይታ ይህ ነው።",
  "Administrator account": "የአስተዳዳሪ መለያ",
  "Workspace preferences": "የስራ ቦታ ምርጫዎች",
  "Manage your administrator account, security, appearance, and data synchronization.": "የአስተዳዳሪ መለያዎን፣ ደህንነትን፣ ገጽታን እና የመረጃ ማመሳሰያን ያስተዳድሩ።",
  "Account": "መለያ",
  "Your current administrator identity.": "የአሁኑ የአስተዳዳሪ መረጃዎ።",
  "Appearance": "ገጽታ",
  "Choose how the management portal looks on this device.": "የአስተዳደር መተግበሪያው በዚህ መሣሪያ እንዴት እንዲታይ ይምረጡ።",
  "Theme": "ገጽታ",
  "Change password": "የይለፍ ቃል ቀይር",
  "Current password": "የአሁኑ ይለፍ ቃል",
  "New password": "አዲስ ይለፍ ቃል",
  "Confirm new password": "አዲሱን ይለፍ ቃል ያረጋግጡ",
  "Data synchronization": "የመረጃ ማመሳሰያ",
  "Synchronize now": "አሁን አመሳስል",
  "Session": "ክፍለ ጊዜ",
  "Language": "ቋንቋ",
  "English": "እንግሊዝኛ",
  "Amharic": "አማርኛ",
  "Welcome back": "እንኳን ደህና መጡ",
  "Sign in to your administrator account to continue.": "ለመቀጠል ወደ አስተዳዳሪ መለያዎ ይግቡ።",
  "Username": "የተጠቃሚ ስም",
  "Password": "የይለፍ ቃል",
  "Sign in": "ግባ",
  "Member management": "የአባላት አስተዳደር",
  "Member directory": "የአባላት ዝርዝር",
  "Register member": "አባል መዝግብ",
  "Register, update, and review the people in your cooperative.": "በህብረት ስራ ማህበሩ ውስጥ ያሉ አባላትን ይመዝግቡ፣ ያሻሽሉ እና ይገምግሙ።",
  "Financial activity": "የገንዘብ እንቅስቃሴ",
  "Track every savings, share, fee, and loan movement.": "እያንዳንዱን የቁጠባ፣ የአክሲዮን፣ የክፍያ እና የብድር እንቅስቃሴ ይከታተሉ።",
  "Record transaction": "ግብይት መዝግብ",
  "Loans": "ብድሮች",
  "New loan application": "አዲስ የብድር ማመልከቻ",
  "Review applications, manage active lending, and track repayment lifecycle.": "ማመልከቻዎችን ይገምግሙ፣ ንቁ ብድሮችን ያስተዳድሩ እና የክፍያ ሂደትን ይከታተሉ።",
  "All members": "ሁሉም አባላት",
  "All types": "ሁሉም አይነቶች",
  "Clear filters": "ማጣሪያዎችን አጽዳ",
  "No members found": "ምንም አባላት አልተገኙም",
  "No transactions found": "ምንም ግብይቶች አልተገኙም",
  "No loans match the selected filters.": "ከተመረጡት ማጣሪያዎች ጋር የሚስማሙ ብድሮች የሉም።",
  "A live view of your cooperative’s savings, members, lending, and operating activity.": "የህብረት ስራ ማህበሩን ቁጠባ፣ አባላት፣ ብድር እና የስራ እንቅስቃሴ በቀጥታ ይመልከቱ።",
  "Recent transactions": "የቅርብ ጊዜ ግብይቶች",
  "The latest activity across your cooperative.": "በህብረት ስራ ማህበሩ የተከናወኑ የቅርብ ጊዜ እንቅስቃሴዎች።",
  "View all": "ሁሉንም ይመልከቱ",
  "No transactions have been recorded yet.": "እስካሁን ምንም ግብይት አልተመዘገበም።",
  "Current loan distribution by status.": "የአሁኑ የብድር ስርጭት በሁኔታ።",
  "Portfolio principal": "የማህደር ዋና ብድር",
  "Open loan portfolio": "ክፍት የብድር ማህደር",
  "Transaction ledger": "የግብይት መዝገብ",
  "No transactions match the selected filters.": "ከተመረጡት ማጣሪያዎች ጋር የሚስማሙ ግብይቶች የሉም።",
  "Transaction details": "የግብይት ዝርዝሮች",
  "Transaction type": "የግብይት አይነት",
  "Notes": "ማስታወሻ",
  "Opening savings balance": "የመነሻ ቁጠባ ቀሪ ሂሳብ",
  "Opening share balance": "የመነሻ አክሲዮን ቀሪ ሂሳብ",
  "Expense register": "የወጪ መዝገብ",
  "No expenses found": "ምንም ወጪዎች አልተገኙም",
  "Annual allocation": "ዓመታዊ ድልድል",
  "Calculation preview": "የስሌት ቅድመ እይታ",
  "Fiscal month": "የበጀት ወር",
  "Month ending": "የወሩ መጨረሻ",
  "Revenue": "ገቢ",
  "Profit": "ትርፍ",
  "Reserve": "የተጠባባቂ ፈንድ",
  "Exit history": "የመውጫ ታሪክ",
  "System operations": "የስርዓት ስራዎች",
  "Queue progress": "የወረፋ ሂደት",
  "Pending rows": "በመጠባበቅ ላይ ያሉ መዝገቦች",
  "Member communication": "የአባላት ግንኙነት",
  "Compose notification": "ማሳወቂያ ጻፍ",
  "Audience": "ተቀባዮች",
  "Title": "ርዕስ",
  "Message": "መልዕክት",
  "Ready to broadcast": "ለስርጭት ዝግጁ",
  "Access control": "የመዳረሻ ቁጥጥር",
  "Administrator accounts": "የአስተዳዳሪ መለያዎች",
  "No administrator accounts found.": "ምንም የአስተዳዳሪ መለያዎች አልተገኙም።",
  "Full name": "ሙሉ ስም",
  "Phone number": "ስልክ ቁጥር",
  "Address": "አድራሻ",
  "Age": "ዕድሜ",
  "Gender": "ጾታ",
  "Male": "ወንድ",
  "Female": "ሴት",
  "Date joined": "የተቀላቀሉበት ቀን",
  "Date": "ቀን",
  "Member": "አባል",
  "Status": "ሁኔታ",
  "Amount": "መጠን",
  "Description": "መግለጫ",
  "Category": "ምድብ",
  "Cancel": "ሰርዝ",
  "Save": "አስቀምጥ",
  "Open": "ክፈት",
  "Dashboard unavailable": "ዳሽቦርዱ አይገኝም",
  "Sign in again to load the dashboard.": "ዳሽቦርዱን ለመጫን እንደገና ይግቡ።",
  "A live view of your cooperative's savings, members, lending, and operating activity.": "የህብረት ስራ ማህበሩን ቁጠባ፣ አባላት፣ ብድር እና የስራ እንቅስቃሴ በቀጥታ ይመልከቱ።",
  "Total savings": "ጠቅላላ ቁጠባ",
  "Recorded savings deposits": "የተመዘገቡ የቁጠባ ገቢዎች",
  "Active members": "ንቁ አባላት",
  "Active loans": "ንቁ ብድሮች",
  "This month’s income": "የዚህ ወር ገቢ",
  "This month's income": "የዚህ ወር ገቢ",
  "total members": "ጠቅላላ አባላት",
  "principal outstanding": "ያልተከፈለ ዋና ብድር",
  "operating expenses": "የስራ ወጪዎች",
  "Active": "ንቁ",
  "Pending review": "ግምገማ በመጠባበቅ ላይ",
  "Closed": "የተዘጋ",
  "Unknown member": "ያልታወቀ አባል",
  "Organization": "ድርጅት",
  "Operations finance": "የስራ ገንዘብ አስተዳደር",
  "Record and review the operating costs that affect monthly profit.": "ወርሃዊ ትርፍን የሚነኩ የስራ ወጪዎችን ይመዝግቡ እና ይገምግሙ።",
  "Visible expenses": "የሚታዩ ወጪዎች",
  "Visible total": "የሚታይ ጠቅላላ",
  "Expenses are ordered from newest to oldest.": "ወጪዎች ከአዲሱ ወደ አሮጌው ተደርድረዋል።",
  "Loading expenses…": "ወጪዎች በመጫን ላይ…",
  "No expenses match the selected category.": "ከተመረጠው ምድብ ጋር የሚስማሙ ወጪዎች የሉም።",
  "Back to expenses": "ወደ ወጪዎች ተመለስ",
  "Operating cost": "የስራ ወጪ",
  "Record expense": "ወጪ መዝግብ",
  "Add a verified expense to the organization’s financial register.": "የተረጋገጠ ወጪ ወደ ድርጅቱ የገንዘብ መዝገብ ያክሉ።",
  "All amounts are recorded in Ethiopian birr.": "ሁሉም መጠኖች በኢትዮጵያ ብር ይመዘገባሉ።",
  "Supplies": "አቅርቦቶች",
  "Utilities": "የመገልገያ አገልግሎቶች",
  "Rent": "ኪራይ",
  "Maintenance": "ጥገና",
  "Equipment": "መሣሪያ",
  "Other": "ሌላ",
  "All categories": "ሁሉም ምድቦች",
  "Select expense date": "የወጪ ቀን ይምረጡ",
  "Expense date": "የወጪ ቀን",
  "What was this expense for?": "ይህ ወጪ ለምን ነበር?",
  "Expense details": "የወጪ ዝርዝሮች",
  "Loading expense…": "ወጪ በመጫን ላይ…",
  "No description was provided.": "ምንም መግለጫ አልተሰጠም።",
  "Recorded on": "የተመዘገበው በ",
  "Recorded by": "የመዘገበው",
  "Expense ID": "የወጪ መለያ",
  "Save expense": "ወጪውን አስቀምጥ",
  "Save this expense?": "ይህን ወጪ እንዲቀመጥ ያድርጉ?",
  "Member lifecycle": "የአባል የህይወት ዑደት",
  "Review a member's balance and dividend entitlement before processing their resignation payout.": "የአባልን የቀሪ ሂሳብ እና የትርፍ ድርሻ መብት ከመውጫ ክፍያ በፊት ይገምግሙ።",
  "Process a member exit": "የአባል መውጫ አስኬድ",
  "The backend checks active loans, guarantor obligations, and calculates the final payout.": "የኋላ ክፍሉ ንቁ ብድሮችን እና የዋስትና ግዴታዎችን ያረጋግጣል፣ የመጨረሻ ክፍያንም ያሰላል።",
  "Exit date": "የመውጫ ቀን",
  "Select an active member": "ንቁ አባል ይምረጡ",
  "Select exit date": "የመውጫ ቀን ይምረጡ",
  "Calculating payout preview…": "የክፍያ ቅድመ እይታ በማስላት ላይ…",
  "Completed resignation payouts.": "የተጠናቀቁ የስራ መልቀቂያ ክፍያዎች።",
  "Loading exit records…": "የመውጫ መዝገቦች በመጫን ላይ…",
  "No member exits have been processed.": "ምንም የአባል መውጫ አልተከናወነም።",
  "Dividend owed": "የሚከፈል የትርፍ ድርሻ",
  "Withholding": "ተቀናሽ",
  "Net payout": "የተጣራ ክፍያ",
  "Completed payout": "የተጠናቀቀ ክፍያ",
  "Net amount paid to the member after government withholding.": "የመንግስት ተቀናሽ ከተደረገ በኋላ ለአባሉ የተከፈለ የተጣራ መጠን።",
  "Savings returned": "የተመለሰ ቁጠባ",
  "Shares returned": "የተመለሱ አክሲዮኖች",
  "Government withholding": "የመንግስት ተቀናሽ",
  "Exit record ID": "የመውጫ መዝገብ መለያ",
  "Preview the fiscal-year profit allocation before saving member dividend records.": "የአባላትን የትርፍ ድርሻ መዝገብ ከማስቀመጥዎ በፊት የበጀት ዓመቱን የትርፍ ድልድል ይመልከቱ።",
  "Calculating fiscal-year preview…": "የበጀት ዓመቱ ቅድመ እይታ በማስላት ላይ…",
  "The backend calculates profit after expenses, then allocates 65% to savings, 20% to shares, and 15% to reserve.": "የኋላ ክፍሉ ከወጪዎች በኋላ ትርፍን ያሰላል፤ ከዚያ 65% ለቁጠባ፣ 20% ለአክሲዮን እና 15% ለተጠባባቂ ፈንድ ይመድባል።",
  "Saved dividend records": "የተቀመጡ የትርፍ ድርሻ መዝገቦች",
  "Loading saved records…": "የተቀመጡ መዝገቦች በመጫን ላይ…",
  "No dividend records have been saved for this fiscal year.": "ለዚህ የበጀት ዓመት ምንም የትርፍ ድርሻ መዝገብ አልተቀመጠም።",
  "Savings dividend": "የቁጠባ ትርፍ ድርሻ",
  "Share dividend": "የአክሲዮን ትርፍ ድርሻ",
  "Total": "ጠቅላላ",
  "Select fiscal year": "የበጀት ዓመት ይምረጡ",
  "Send targeted messages or broadcast important updates to active members.": "ለተወሰኑ አባላት መልዕክት ይላኩ ወይም ጠቃሚ ዝመናዎችን ለንቁ አባላት ያሰራጩ።",
  "Broadcasts are sent to active members only.": "ስርጭቶች የሚላኩት ለንቁ አባላት ብቻ ነው።",
  "All active members": "ሁሉም ንቁ አባላት",
  "One member": "አንድ አባል",
  "Optional related loan ID": "አማራጭ የተያያዘ የብድር መለያ",
  "Notification title": "የማሳወቂያ ርዕስ",
  "Write the message members should receive…": "አባላት ሊቀበሉት የሚገባ መልዕክት ይጻፉ…",
  "Preview failed": "ቅድመ እይታው አልተሳካም",
  "Notification not sent": "ማሳወቂያው አልተላከም",
  "Notification sent": "ማሳወቂያው ተልኳል",
  "The broadcast was created for active members.": "ስርጭቱ ለንቁ አባላት ተፈጥሯል።",
  "The notification was created successfully.": "ማሳወቂያው በተሳካ ሁኔታ ተፈጥሯል።",
  "Preview recipients": "ተቀባዮችን ቅድመ ይመልከቱ",
  "Checking…": "በመመርመር ላይ…",
  "Sending…": "በመላክ ላይ…",
  "Notification inbox": "የማሳወቂያ ሳጥን",
  "Recent notifications and delivery status.": "የቅርብ ጊዜ ማሳወቂያዎች እና የመድረስ ሁኔታ።",
  "All statuses": "ሁሉም ሁኔታዎች",
  "Unread": "ያልተነበበ",
  "Read": "የተነበበ",
  "No notifications match the selected filters.": "ከተመረጡት ማጣሪያዎች ጋር የሚስማሙ ማሳወቂያዎች የሉም።",
  "Mark read": "እንደተነበበ ምልክት አድርግ",
  "Monitor the local queue, check remote connectivity, and synchronize cooperative data.": "የአካባቢ ወረፋን ይከታተሉ፣ የርቀት ግንኙነትን ይመርምሩ እና የህብረት ስራ ማህበሩን መረጃ ያመሳስሉ።",
  "Unable to check sync status": "የማመሳሰያ ሁኔታን ማረጋገጥ አልተቻለም",
  "Synchronization completed": "ማመሳሰያው ተጠናቋል",
  "Synchronization completed with errors": "ማመሳሰያው ከስህተቶች ጋር ተጠናቋል",
  "All local changes are synchronized.": "ሁሉም የአካባቢ ለውጦች ተመሳስለዋል።",
  "Up to date": "የተዘመነ",
  "Pending changes": "በመጠባበቅ ላይ ያሉ ለውጦች",
  "Waiting for sync": "ማመሳሰያን በመጠባበቅ ላይ",
  "Local sync queue": "የአካባቢ ማመሳሰያ ወረፋ",
  "Rows with pending changes waiting to be pushed to the remote database.": "ለውጦች ያሉባቸው ወደ ርቀት ዳታቤዝ ለመላክ በመጠባበቅ ላይ ያሉ መዝገቦች።",
  "Refresh status": "ሁኔታን አድስ",
  "Loading synchronization status…": "የማመሳሰያ ሁኔታ በመጫን ላይ…",
  "No table status is available.": "ምንም የሰንጠረዥ ሁኔታ አይገኝም።",
  "Table": "ሰንጠረዥ",
  "Latest run details": "የቅርብ ጊዜ ሂደት ዝርዝሮች",
  "Per-table results from the most recent synchronization.": "ከቅርብ ጊዜ ማመሳሰያ የተገኙ የእያንዳንዱ ሰንጠረዥ ውጤቶች።",
  "Found": "የተገኘ",
  "Pushed": "የተላከ",
  "Skipped": "የተዘለለ",
  "Remote connection": "የርቀት ግንኙነት",
  "The service checks the remote PostgreSQL connection before reporting health.": "አገልግሎቱ የርቀት PostgreSQL ግንኙነትን ጤንነት ከማሳወቁ በፊት ይመረምራል።",
  "Connected": "ተገናኝቷል",
  "Unavailable": "አይገኝም",
  "Only active administrators can sign in.": "ንቁ አስተዳዳሪዎች ብቻ መግባት ይችላሉ።",
  "Loading administrator accounts…": "የአስተዳዳሪ መለያዎች በመጫን ላይ…",
  "Manage the people who can access and operate the cooperative management portal.": "የህብረት ስራ ማህበሩን የአስተዳደር መተግበሪያ መግባትና መጠቀም የሚችሉ ሰዎችን ያስተዳድሩ።",
  "Created": "የተፈጠረ",
  "New administrator": "አዲስ አስተዳዳሪ",
  "Create an account for a trusted cooperative operator.": "ለታማኝ የህብረት ስራ ማህበር አስተዳዳሪ መለያ ይፍጠሩ።",
  "Temporary password": "ጊዜያዊ ይለፍ ቃል",
  "Administrator created successfully.": "አስተዳዳሪው በተሳካ ሁኔታ ተፈጥሯል።",
  "Create administrator": "አስተዳዳሪ ፍጠር",
  "Creating…": "በመፍጠር ላይ…",
  "Search name or phone": "በስም ወይም በስልክ ይፈልጉ",
  "Search members": "አባላትን ይፈልጉ",
  "Filter by member": "በአባል አጣራ",
  "Filter by transaction type": "በግብይት አይነት አጣራ",
  "Filter expenses by category": "ወጪዎችን በምድብ አጣራ",
  "Filter by notification type": "ማሳወቂያዎችን በአይነት አጣራ",
  "Filter by read status": "በንባብ ሁኔታ አጣራ",
  "From date": "ከቀን",
  "To date": "እስከ ቀን",
  "Select a member": "አባል ይምረጡ",
  "Select a member to view their collection summary.": "የአባሉን የስብስብ ማጠቃለያ ለማየት አባል ይምረጡ።",
}

export function translatedText(value, language) {
  if (language !== "am" || typeof value !== "string") return value
  const trimmed = value.trim()
  const translated = translations[trimmed]
  if (translated) return value.replace(trimmed, translated)

  const prefix = Object.keys(translations)
    .filter((key) => trimmed.startsWith(key + " "))
    .sort((left, right) => right.length - left.length)[0]
  if (prefix) return value.replace(prefix, translations[prefix])

  const fragment = Object.keys(translations)
    .filter((key) => key.length > 4 && trimmed.includes(key))
    .sort((left, right) => right.length - left.length)[0]
  return fragment ? value.replace(fragment, translations[fragment]) : value
}
